export const LANG = {
  EN: {
    UNKNOWN_ERROR: "Unknown error!",
    INVALID_AUTH_HEADER: "Invalid Authorization header!",
    EXPIRED_TOKEN: "Token expired!",
    INVALID_TOKEN: "Invalid token!",
    EMAIL_NOT_FOUND: "Email not found!",
    USER_NOT_FOUND: "User not found!",
    USER_PASSWORD_IS_INCORRENT: "Password is incorrect!",
    USER_EXISTS: "User already exists!",
    REFRESH_TOKEN_INVALID: "Refresh token invalid!",
    REFRESH_TOKEN_EXPIRED: "Refresh token expired!",
    USER_REGISTERED_SUCCESSFULLY: "User registered successfully.",
    LOGIN_SUCCESS: "Login success.",
    TOKEN_REFRESHED: "Token refreshed.",
    USER_FOUND: "User found.",
    EMAIL_IS_INCORRECT: "Email is incorrect!",
    FAILED_TO_SEND_OTP: "Failed to send OTP!",
    EMAIL_SENT_SUCCESSFULLY: "Email sent successfully.",
    INVALID_OTP: "Invalid OTP!",
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
    USER_EMAIL_EXISTS: "Email already exists!",
    USER_PASSWORD_INVALID: "Password is invalid!",
    USER_UPDATED_SUCCESSFULLY: "User updated successfully.",
    PASSWORD_VALIDATION_MESSAGE:
      "The password must contain at least one letter and one number!",
    EMAIL_VALIDATION_MESSAGE: "Email is not valid!",
    API_STATUS_MESSAGE: "Api status listed successfully.",
    DATABASE_SYNC_SUCCESS: "Database sync success.",
  },
  TR: {
    UNKNOWN_ERROR: "Bilinmeyen hata!",
    INVALID_AUTH_HEADER: "Geçersiz Authorization başlığı!",
    EXPIRED_TOKEN: "Token süresi doldu!",
    INVALID_TOKEN: "Geçersiz token!",
    EMAIL_NOT_FOUND: "Email bulunamadı!",
    USER_NOT_FOUND: "Kullanıcı bulunamadı!",
    USER_PASSWORD_IS_INCORRENT: "Şifre yanlış!",
    USER_EXISTS: "Kullanıcı zaten mevcut!",
    REFRESH_TOKEN_INVALID: "Yenileme tokeni geçersiz!",
    REFRESH_TOKEN_EXPIRED: "Yenileme tokeni süresi doldu!",
    USER_REGISTERED_SUCCESSFULLY: "Kullanıcı başarıyla kaydedildi.",
    LOGIN_SUCCESS: "Giriş başarılı.",
    TOKEN_REFRESH: "Token yenilendi.",
    USER_FOUND: "Kullanıcı bulundu.",
    EMAIL_IS_INCORRECT: "Email yanlış!",
    FAILED_TO_SEND_OTP: "OTP gönderilemedi!",
    EMAIL_SENT_SUCCESSFULLY: "Email başarıyla gönderildi.",
    INVALID_OTP: "Geçersiz OTP!",
    PASSWORD_UPDATED_SUCCESSFULLY: "Şifre başarıyla güncellendi.",
    USER_EMAIL_EXISTS: "Email zaten mevcut!",
    USER_PASSWORD_INVALID: "Şifre geçersiz!",
    USER_UPDATED_SUCCESSFULLY: "Kullanıcı başarıyla güncellendi.",
    PASSWORD_VALIDATION_MESSAGE:
      "Şifre en az bir harf ve bir rakam içermelidir!",
    EMAIL_VALIDATION_MESSAGE: "Email geçerli değil!",
    API_STATUS_MESSAGE: "Api durumu başarıyla listelendi.",
    DATABASE_SYNC_SUCCESS: "Veritabanı senkronizasyonu başarılı.",
  },
};
