export const LANG = {
  EN: {
    DEFAULT: "Error description not found!",
    INVALID_AUTH_HEADER: "Invalid Authorization header!",
    EXPIRED_TOKEN: "Token expired!",
    INVALID_TOKEN: "Invalid token!",
    EMAIL_NOT_FOUND: "Email not found!",
    USER_NOT_FOUND: "User not found!",
    USER_PASSWORD_IS_INCORRENT: "Password is incorrect!",
    USER_EXISTS: "User already exists!",
    REFRESH_TOKEN_INVALID: "Refresh token invalid!",
    REFRESH_TOKEN_EXPIRED: "Refresh token expired!",
    USER_REGISTERED_SUCCESSFULLY: "User registered successfully.",
    LOGIN_SUCCESS: "Login success.",
    USER_FOUND: "User found.",
    EMAIL_IS_INCORRECT: "Email is incorrect!",
    FAILED_TO_SEND_OTP: "Failed to send OTP!",
    EMAIL_SENT_SUCCESSFULLY: "Email sent successfully.",
    INVALID_OTP: "Invalid OTP!",
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
    USER_EMAIL_EXISTS: "Email already exists!",
    USER_PASSWORD_INVALID: "Password is invalid!",
    USER_UPDATED_SUCCESSFULLY: "User updated successfully.",
    PASSWORD_VALIDATION_MESSAGE:
      "The password must contain at least one letter and one number!",
    EMAIL_VALIDATION_MESSAGE: "Email is not valid!",
    API_STATUS_MESSAGE: "Api status listed successfully.",
    DATABASE_SYNC_SUCCESS: "Database sync success.",
    PASSWORD_REQUIREMENTS:
      "The password must contain at least one letter and one number!",
    PASSWORD_STRING_MIN: "Password must be at least 8 characters!",
    PASSWORD_REQUIRED: "Password is required!",
    PASSWORD_CANNOT_BE_EMPTY: "Password is cannot be empty!",
    PASSWORD_STRING_MAX: "Password must be at most 20 characters!",
    EMAIL_REQUIRED: "Email is required!",
    EMAIL_CANNOT_BE_EMPTY: "Email is cannot be empty!",
    EMAIL_MIN: "Email must be at least 3 characters!",
    EMAIL_MAX: "Email must be at most 20 characters!",
    USERNAME_REQUIRED: "Username is required!",
    USERNAME_CANNOT_BE_EMPTY: "Username is cannot be empty!",
    USERNAME_MIN: "Username must be at least 3 characters!",
    USERNAME_MAX: "Username must be at most 20 characters!",
    LASTNAME_REQUIRED: "Lastname is required!",
    LASTNAME_CANNOT_BE_EMPTY: "Lastname is cannot be empty!",
    LASTNAME_MIN: "Lastname must be at least 3 characters!",
    LASTNAME_MAX: "Lastname must be at most 20 characters!",
    FIRSTNAME_REQUIRED: "Firstname is required!",
    FIRSTNAME_CANNOT_BE_EMPTY: "Firstname is cannot be empty!",
    FIRSTNAME_MIN: "Firstname must be at least 3 characters!",
    FIRSTNAME_MAX: "Firstname must be at most 20 characters!",
    OTP_LENGTH: "OTP must be 6 characters!",
    OTP_REQUIRED: "OTP is required!",
    CLASS_NAME_MIN: "Class name must be at least 2 characters!",
    CLASS_NAME_MAX: "Class name must be at most 3 characters!",
    CLASS_NAME_REQUIRED: "Class name is required!",
    EXPLANATION_MIN: "Explanation must be at least 2 characters!",
    GRADE_TYPE_MIN: "Grade type must be at least 3 characters!",
    GRADE_VALUE_NUMBER: "Grade value must be a number!",
    GRADE_VALUE_OPTIONAL: "Grade value is optional!",
    GRADE_VALUE_ALLOW: "Grade value is optional!",
    ID_NUMBER_CHARACTER: "ID Number must be exactly 11 digits long!",
    ID_NUMBER_NUMBER: "ID Number must be a number!",
    ID_NUMBER_REQUIRED: "ID Number is required!",
    ID_NUMBER_INTEGER: "ID Number must be an integer!",
    ID_NUMBER_CANNOT_BE_EMPTY: "ID Number cannot be empty!",
    NUMBER_INVALID: "Number must be between 2 and 15 characters long!",
    NUMBER_REQUIRED: "Number is required!",
    NUMBER_CANNOT_BE_EMPTY: "Number is cannot be empty!",
    GENDER_VALIDATION_MESSAGE: "Gender must be one of Female or Male!",
    GENDER_REQUIRED: "Gender is required!",
    GENDER_EMPTY: "Gender cannot be empty!",
    BIRTHDAY_REQUIRED: "Birthday is required!",
    BIRTHDAY_CANNOT_BE_EMPTY: "Birthday is cannot be empty!",
    BIRTHDAY_INVALID: "Birthday is invalid!",
    STUDENT_ID_NUMBER: "Student id must be a number!",
    STUDENT_ID_REQUIRED: "Student id is required!",
    STUDENT_ID_INTEGER: "Student id must be an integer!",
    TITLE_REQUIRED: "Title is required!",
    TITLE_CANNOT_BE_EMPTY: "Title cannot be empty!",
    TITLE_MIN: "Title must be at least 3 characters!",
    TITLE_MAX: "Title must be at most 20 characters!",
    NOTE_REQUIRED: "Note is required!",
    NOTE_CANNOT_BE_EMPTY: "Note cannot be empty!",
    NOTE_MIN: "Note must be at least 3 characters!",
    NOTE_MAX: "Note must be at most 130 characters!",
    REFRESH_TOKEN_REQUIRED: "Refresh token is required!",
    REFRESH_TOKEN_EMPTY: "Refresh token cannot be empty!",
    TOKEN_SUCCESS_REFRESHED: "Token refreshed successfully.",
    ROUTE_NOT_FOUND: "Route not found:",
    NO_AUTH_HEADER: "No Authorization header!",
    NO_TOKEN: "No token!",
    INVALID_CLASS: "Invalid class!",
    CLASS_ALREADY_EXISTS: "Class already exists!",
    CLASS_CREATED: "Class created successfully.",
    CLASSES_FOUND: "Classes found.",
    CLASS_COUNT_FOUND: "Class count found.",
    INVALID_CLASS_ID: "Invalid class id!",
    CLASS_UPDATED: "Class updated successfully.",
    TEACHER_DOES_NOT_HAVE_CLASS: "Teacher does not have a class!",
    CLASS_SUCCESS_DELETED: "Class successfully deleted.",
    CLASS_ID_REQUIRED: "Class id is required!",
    CLASS_ID_INTEGER: "Class id must be an integer!",
    STUDENT_COUNT_FOUND: "Student count found.",
    STUDENTS_FOUND: "Students found.",
    STUDENT_GENDER_COUNT_FOUND: "Student gender count found.",
    CLASS_ID_STUDENTS_FOUND: "Students found by class.",
    NUMBER_OF_STUDENTS_BY_CLASS_FOUND: "Number of students by class found.",
    STUDENT_ALREADY_EXISTS: "Student already exists!",
    ID_NUMBER_ALREADY_EXISTS: "ID Number has already been used!",
    INVALID_DATE: "Invalid date!",
    ID_REQUIRED: "ID is required!",
    ID_NUMBER: "ID must be a number!",
    ID_INTEGER: "ID must be an integer!",
    STUDENT_DELETED: "Student successfully deleted.",
    CLASS_NOT_FOUND: "Class not found!",
    STUDENT_CREATED: "Student created successfully.",
    NUMBER_EXISTS: "Number already exists!",
    EMAIL_EXISTS: "Email already exists!",
    USERNAME_EXISTS: "Username already exists!",
    USER_USERNAME_EXISTS: "Username already exists!",
    NUMBER_ALREADY_EXISTS: "Number already exists!",
    STUDENT_NOT_FOUND: "Student not found!",
    STUDENT_UPDATED: "Student updated successfully.",
    LATEST_GRADE_FOUND: "Latest grade found.",
    CLASS_ID_GRADES_FOUND: "Class grades found.",
    CLASS_ID_GRADES_NOT_FOUND: "Class grades not found.",
    THERE_IS_NOTE_FOR_THIS_CLASS: "There is a note for this class!",
    CLASS_ID_GRADE_TYPE_FOUND: "Grade type found for class.",
    GRADE_TYPE_MAX: "Grade type must be at most 30 characters!",
    GRADE_TYPE_REQUIRED: "Grade type is required!",
    GRADE_VALUE_REQUIRED: "Grade value is required!",
    GRADE_VALUE_MIN: "Grade value must be at least 3 characters!",
    STUDENT_NOT_FOUND_IN_THE_CLASS: "Student not found in the specified class",
    GRADE_VALUE_INTEGER: "Grade value must be an integer!",
    GRADE_ID_NUMBER: "Grade id must be a number!",
    GRADE_ID_REQUIRED: "Grade id is required!",
    GRADE_ID_INTEGER: "Grade id must be an integer!",
    CLASS_NAME_EMPTY: "Class name cannot be empty!",
    EXPLANATION_EMPTY: "Explanation cannot be empty!",
    CLASS_ID_EMPTY: "Class id cannot be empty!",
    ID_CANNOT_BE_EMPTY: "ID cannot be empty!",
    GRADE_TYPE_EMPTY: "Grade type cannot be empty!",
    GRADE_VALUE_EMPTY: "Grade value cannot be empty!",
    GRADE_ID_EMPTY: "Grade id cannot be empty!",
    OTP_EMPTY: "OTP cannot be empty!",
    GRADE_CREATED: "Grade created successfully.",
    GRADE_TYPE_EXISTS: "Grade type already exists!",
    GRADE_TYPE_NOT_FOUND: "Grade type not found!",
    GRADE_UPDATED: "Grade updated successfully.",
    GRADE_NOT_FOUND: "Grade not found!",
    GRADE_VALUE_NUMBER_MIN: "Grade value must be at least 0!",
    GRADE_VALUE_NUMBER_MAX: "Grade value must be at most 100!",
    USER_ID_REQUIRED: "User ID is required!",
    USER_ID_NUMBER: "User ID must be a number!",
    USER_ID_INTEGER: "User ID must be an integer!",
    USER_ID_EMPTY: "User ID cannot be empty!",
    GRADES_FOUND: "Grades found.",
    GRADE_DELETED: "Grade successfully deleted.",
  },
  TR: {
    DEFAULT: "Hata tanımı bulunamadı!",
    INVALID_AUTH_HEADER: "Geçersiz Authorization başlığı!",
    EXPIRED_TOKEN: "Token süresi doldu!",
    INVALID_TOKEN: "Geçersiz token!",
    EMAIL_NOT_FOUND: "E-Posta bulunamadı!",
    USER_NOT_FOUND: "Kullanıcı bulunamadı!",
    USER_PASSWORD_IS_INCORRENT: "Şifre yanlış!",
    USER_EXISTS: "Kullanıcı zaten mevcut!",
    REFRESH_TOKEN_INVALID: "Yenileme tokeni geçersiz!",
    REFRESH_TOKEN_EXPIRED: "Yenileme tokeni süresi doldu!",
    USER_REGISTERED_SUCCESSFULLY: "Kullanıcı başarıyla kaydedildi.",
    LOGIN_SUCCESS: "Giriş başarılı.",
    TOKEN_REFRESH: "Token yenilendi.",
    USER_FOUND: "Kullanıcı bulundu.",
    EMAIL_IS_INCORRECT: "E-Posta yanlış!",
    FAILED_TO_SEND_OTP: "OTP gönderilemedi!",
    EMAIL_SENT_SUCCESSFULLY: "E-Posta başarıyla gönderildi.",
    INVALID_OTP: "Geçersiz OTP!",
    PASSWORD_UPDATED_SUCCESSFULLY: "Şifre başarıyla güncellendi.",
    USER_EMAIL_EXISTS: "E-Posta zaten mevcut!",
    USER_PASSWORD_INVALID: "Şifre geçersiz!",
    USER_UPDATED_SUCCESSFULLY: "Kullanıcı başarıyla güncellendi.",
    PASSWORD_VALIDATION_MESSAGE:
      "Şifre en az bir harf ve bir rakam içermelidir!",
    EMAIL_VALIDATION_MESSAGE: "E-Posta geçerli değil!",
    API_STATUS_MESSAGE: "Api durumu başarıyla listelendi.",
    DATABASE_SYNC_SUCCESS: "Veritabanı senkronizasyonu başarılı.",
    PASSWORD_REQUIREMENTS: "Şifre en az bir harf ve bir rakam içermelidir!",
    PASSWORD_STRING_MIN: "Şifre en az 8 karakter olmalıdır!",
    PASSWORD_REQUIRED: "Şifre gereklidir!",
    PASSWORD_CANNOT_BE_EMPTY: "Şifre boş olamaz!",
    PASSWORD_STRING_MAX: "Şifre en fazla 20 karakter olmalıdır!",
    EMAIL_REQUIRED: "E-Posta gereklidir!",
    EMAIL_CANNOT_BE_EMPTY: "E-Posta boş olamaz!",
    EMAIL_MIN: "E-Posta en az 3 karakter olmalıdır!",
    EMAIL_MAX: "E-Posta en fazla 20 karakter olmalıdır!",
    USERNAME_REQUIRED: "Kullanıcı adı gereklidir!",
    USERNAME_CANNOT_BE_EMPTY: "Kullanıcı adı boş olamaz!",
    USERNAME_MIN: "Kullanıcı adı en az 3 karakter olmalıdır!",
    USERNAME_MAX: "Kullanıcı adı en fazla 20 karakter olmalıdır!",
    LASTNAME_REQUIRED: "Soyadı gereklidir!",
    LASTNAME_CANNOT_BE_EMPTY: "Soyadı boş olamaz!",
    LASTNAME_MIN: "Soyadı en az 3 karakter olmalıdır!",
    LASTNAME_MAX: "Soyadı en fazla 20 karakter olmalıdır!",
    FIRSTNAME_REQUIRED: "Ad gereklidir!",
    FIRSTNAME_CANNOT_BE_EMPTY: "Ad boş olamaz!",
    FIRSTNAME_MIN: "Ad en az 3 karakter olmalıdır!",
    FIRSTNAME_MAX: "Ad en fazla 20 karakter olmalıdır!",
    OTP_LENGTH: "OTP 6 karakter olmalıdır!",
    OTP_REQUIRED: "OTP gereklidir!",
    CLASS_NAME_MIN: "Sınıf adı en az 2 karakter olmalıdır!",
    CLASS_NAME_MAX: "Sınıf adı en fazla 3 karakter olmalıdır!",
    CLASS_NAME_REQUIRED: "Sınıf adı gereklidir!",
    EXPLANATION_MIN: "Açıklama en az 2 karakter olmalıdır!",
    GRADE_TYPE_MIN: "Not türü en az 3 karakter olmalıdır!",
    GRADE_VALUE_NUMBER: "Not değeri bir sayı olmalıdır!",
    GRADE_VALUE_OPTIONAL: "Not değeri isteğe bağlıdır!",
    GRADE_VALUE_ALLOW: "Not değeri isteğe bağlıdır!",
    ID_NUMBER_CHARACTER: "TC tam olarak 11 basamaklı olmalıdır!",
    ID_NUMBER_NUMBER: "TC bir sayı olmalıdır!",
    ID_NUMBER_REQUIRED: "TC gereklidir!",
    ID_NUMBER_INTEGER: "TC bir tam sayı olmalıdır!",
    ID_NUMBER_CANNOT_BE_EMPTY: "TC boş olamaz!",
    NUMBER_INVALID: "Öğrenci Numarası 2 ile 15 karakter arasında olmalıdır!",
    NUMBER_REQUIRED: "Öğrenci numarası gereklidir!",
    NUMBER_CANNOT_BE_EMPTY: "Öğrenci numarası boş olamaz!",
    GENDER_VALIDATION_MESSAGE: "Cinsiyet Kız veya Erkek olmalıdır!",
    GENDER_REQUIRED: "Cinsiyet gereklidir!",
    GENDER_EMPTY: "Cinsiyet boş olamaz!",
    BIRTHDAY_REQUIRED: "Doğum tarihi gereklidir!",
    BIRTHDAY_CANNOT_BE_EMPTY: "Doğum tarihi boş olamaz!",
    BIRTHDAY_INVALID: "Doğum tarihi geçersiz!",
    STUDENT_ID_NUMBER: "Öğrenci id bir sayı olmalıdır!",
    STUDENT_ID_REQUIRED: "Öğrenci id gereklidir!",
    STUDENT_ID_INTEGER: "Öğrenci id bir tam sayı olmalıdır!",
    TITLE_REQUIRED: "Başlık gereklidir!",
    TITLE_CANNOT_BE_EMPTY: "Başlık boş olamaz!",
    TITLE_MIN: "Başlık en az 3 karakter olmalıdır!",
    TITLE_MAX: "Başlık en fazla 20 karakter olmalıdır!",
    NOTE_REQUIRED: "Not gereklidir!",
    NOTE_CANNOT_BE_EMPTY: "Not boş olamaz!",
    NOTE_MIN: "Not en az 3 karakter olmalıdır!",
    NOTE_MAX: "Not en fazla 130 karakter olmalıdır!",
    REFRESH_TOKEN_REQUIRED: "Yenileme tokeni gereklidir!",
    REFRESH_TOKEN_EMPTY: "Yenileme tokeni boş olamaz!",
    TOKEN_SUCCESS_REFRESHED: "Token başarıyla yenilendi.",
    ROUTE_NOT_FOUND: "Rota bulunamadı:",
    NO_AUTH_HEADER: "Yetkilendirme başlığı yok!",
    NO_TOKEN: "Token yok!",
    INVALID_CLASS: "Geçersiz sınıf!",
    CLASS_ALREADY_EXISTS: "Sınıf zaten mevcut!",
    CLASS_CREATED: "Sınıf başarıyla oluşturuldu.",
    CLASSES_FOUND: "Sınıflar bulundu.",
    CLASS_COUNT_FOUND: "Sınıf sayısı bulundu.",
    INVALID_CLASS_ID: "Geçersiz sınıf id'si!",
    CLASS_UPDATED: "Sınıf başarıyla güncellendi.",
    TEACHER_DOES_NOT_HAVE_CLASS: "Öğretmen sınıfa sahip değil!",
    CLASS_SUCCESS_DELETED: "Sınıf başarıyla silindi.",
    CLASS_ID_REQUIRED: "Sınıf id'si gereklidir!",
    CLASS_ID_INTEGER: "Sınıf id'si bir tam sayı olmalıdır!",
    STUDENT_COUNT_FOUND: "Öğrenci sayısı bulundu.",
    STUDENTS_FOUND: "Öğrenciler bulundu.",
    STUDENT_GENDER_COUNT_FOUND: "Öğrenci cinsiyet sayısı bulundu.",
    CLASS_ID_STUDENTS_FOUND: "Sınıfa göre öğrenciler bulundu.",
    NUMBER_OF_STUDENTS_BY_CLASS_FOUND: "Sınıfa göre öğrenci sayısı bulundu.",
    STUDENT_ALREADY_EXISTS: "Öğrenci zaten mevcut!",
    ID_NUMBER_ALREADY_EXISTS: "TC kimlik numarası zaten kullanılmış!",
    INVALID_DATE: "Geçersiz tarih!",
    ID_REQUIRED: "ID gereklidir!",
    ID_NUMBER: "ID bir sayı olmalıdır!",
    ID_INTEGER: "ID bir tam sayı olmalıdır!",
    STUDENT_DELETED: "Öğrenci başarıyla silindi.",
    CLASS_NOT_FOUND: "Sınıf bulunamadı!",
    STUDENT_CREATED: "Öğrenci başarıyla oluşturuldu.",
    NUMBER_EXISTS: "Öğrenci numarası zaten mevcut!",
    EMAIL_EXISTS: "E-Posta zaten mevcut!",
    USERNAME_EXISTS: "Kullanıcı adı zaten mevcut!",
    USER_USERNAME_EXISTS: "Kullanıcı adı zaten mevcut!",
    NUMBER_ALREADY_EXISTS: "Öğrenci numarası zaten mevcut!",
    STUDENT_NOT_FOUND: "Öğrenci bulunamadı!",
    STUDENT_UPDATED: "Öğrenci başarıyla güncellendi.",
    LATEST_GRADE_FOUND: "Son girilen not bulundu.",
    CLASS_ID_GRADES_FOUND: "Sınıf notları bulundu.",
    CLASS_ID_GRADES_NOT_FOUND: "Sınıf notları bulunamadı.",
    THERE_IS_NOTE_FOR_THIS_CLASS: "Bu sınıf için not var!",
    CLASS_ID_GRADE_TYPE_FOUND: "Sınıf için not türü bulundu.",
    GRADE_TYPE_MAX: "Not türü en fazla 30 karakter olmalıdır!",
    GRADE_TYPE_REQUIRED: "Not türü gereklidir!",
    GRADE_VALUE_REQUIRED: "Not değeri gereklidir!",
    GRADE_VALUE_MIN: "Not değeri en az 3 karakter olmalıdır!",
    STUDENT_NOT_FOUND_IN_THE_CLASS: "Öğrenci belirtilen sınıfta bulunamadı",
    GRADE_VALUE_INTEGER: "Not değeri bir tam sayı olmalıdır!",
    GRADE_ID_NUMBER: "Not id bir sayı olmalıdır!",
    GRADE_ID_REQUIRED: "Not id gereklidir!",
    GRADE_ID_INTEGER: "Not id bir tam sayı olmalıdır!",
    CLASS_NAME_EMPTY: "Sınıf adı boş olamaz!",
    EXPLANATION_EMPTY: "Açıklama boş olamaz!",
    CLASS_ID_EMPTY: "Sınıf id'si boş olamaz!",
    ID_CANNOT_BE_EMPTY: "ID boş olamaz!",
    GRADE_TYPE_EMPTY: "Not türü boş olamaz!",
    GRADE_VALUE_EMPTY: "Not değeri boş olamaz!",
    GRADE_ID_EMPTY: "Not id'si boş olamaz!",
    OTP_EMPTY: "OTP boş olamaz!",
    GRADE_CREATED: "Not başarıyla oluşturuldu.",
    GRADE_TYPE_EXISTS: "Not türü zaten mevcut!",
    GRADE_TYPE_NOT_FOUND: "Not türü bulunamadı!",
    GRADE_UPDATED: "Not başarıyla güncellendi.",
    GRADE_NOT_FOUND: "Not bulunamadı!",
    GRADE_VALUE_NUMBER_MIN: "Not değeri en az 0 olmalıdır!",
    GRADE_VALUE_NUMBER_MAX: "Not değeri en fazla 100 olmalıdır!",
    USER_ID_REQUIRED: "Kullanıcı ID'si gereklidir!",
    USER_ID_NUMBER: "Kullanıcı ID'si bir sayı olmalıdır!",
    USER_ID_INTEGER: "Kullanıcı ID'si bir tam sayı olmalıdır!",
    USER_ID_EMPTY: "Kullanıcı ID'si boş olamaz!",
    GRADES_FOUND: "Notlar bulundu.",
    GRADE_DELETED: "Not başarıyla silindi.",
  },
};
